name: kulture
description: "Dating App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  bot_toast: ^4.1.3
  image_picker: ^1.1.2
  logger: ^2.4.0
  flutter_native_splash: ^2.4.1
  cached_network_image: ^3.4.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  photo_view: ^0.15.0
  equatable: ^2.0.5
  dio: ^5.5.0+1
  shared_preferences: ^2.3.1
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.6
  intl: ^0.20.2
  reorderables: ^0.6.0
  sizer: ^3.0.4
  flutter_otp_text_field:
  jumping_dot: ^0.0.7
  url_launcher: ^6.3.1
  file_picker: ^8.3.7
  flutter_launcher_icons:
  intl_phone_field:
  carousel_slider: ^5.0.0
  flutter_credit_card: ^4.1.0
  flutter_card_swiper: ^7.0.2
  flutter_staggered_grid_view: ^0.7.0
 

  google_fonts: ^6.2.1
  pin_code_fields:
  dotted_border: ^2.1.0
  confetti: ^0.8.0
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    # - assets/tabicons/
    - assets/images/
    # - assets/images/grid_pics/
    - assets/png/
    - assets/png/backIcon.png
    - assets/png/like.png
    - assets/png/comment.png
    - assets/png/send.png
    - assets/png/save.png


